### ISSUE TITLE
start and end id in Constituents parse

### ISSUE THREAD

**Issue by elahi123** [lapps-clarin/converter-issues#10]
Start and End id appear when LIF is generated by LAPPS Stanford constituent parser tool but not when TCF to LIF converter. This is probably because the parser is a region in WSEV.

a) LIF generated by LAPPS Stanford dependency parse tool (latest version):
{
                        "id": "ps_0",
                        "start": 0,
                        "end": 23,
                        "@type": "http://vocab.lappsgrid.org/PhraseStructure",
                        "features": {
                            "sentence": "Karen flew to New York.",
                            "penntree": "(ROOT [40.118]\n  (S [39.965]\n    (NP [12.050] (NNP Karen))\n    (VP [26.780] (VBD flew)\n      (PP [14.690] (TO to)\n        (NP [12.219] (NNP New) (NNP York))))\n    (. .)))\n",
                            "constituents": ["c_0_0", "c_0_1", "c_0_2", "c_0_3", "c_0_4", "c_0_5", "c_0_6", "c_0_7", "c_0_8", "c_0_9", "c_0_10", "c_0_11"]
                        }
                    }

b) LIF generated by TCF to LIF converter:
{
                        "id": "ps_0",
                        "@type": "http://vocab.lappsgrid.org/PhraseStructure",
                        "features": {
                            "constituents": ["c_0_0", "c_0_1", "c_0_2", "c_0_3", "c_0_4", "c_0_5", "c_0_6", "c_0_7", "c_0_8", "c_0_9", "c_0_10", "c_0_11", "t_0", "t_1", "t_2", "t_3", "t_4", "t_5"]
                        }
                    }
From LIF to TCF conversion, it is necessary to have sentence or region.

**Comment by ksuderman** [comment]
This issue was moved to lappsgrid-services/org.lappsgrid.converters.tcf#26
