### ISSUE TITLE
view referencing

### ISSUE THREAD

**Issue by keighrim** [lapps-clarin/converter-issues#2]
originally from @elahi123 via an e-mail

---
After TCF to LIF converter, the token layer is referring by view ID

```json
{
                        "id": "c_0_10",
                        "label": "VBD",
                        "features": {
                            "parent": "c_0_6",
                            "children": "[**token-view:t_1**]"
                        }
```

I am not trying this case in my converter. That is to convert from LIF to TCF when one view refer other.
However, The example file I have presents list as a string. 

```json
{
                        "id": "c_0_3",
                        "label": "VP",
                        "features": {
                            "parent": "c_0_1",
                            "children": "[**c_0_6, c_0_7**]"      **should be ["c_0_6, c_0_7"]**
                        }
                    }
```

I remember talking about this issue before Tübingen meeting and you fixed it.
Can you please give an example file with all layer (after TCF to LIF) converter where view reference exist?

**Comment by ksuderman** [comment]
This issue was moved to lappsgrid-services/org.lappsgrid.converters.tcf#23
