### ISSUE TITLE
token ids constituent list 

### ISSUE THREAD

**Issue by elahi123** [lapps-clarin/converter-issues#4]
{
                        "id": "ps_0",
                        "@type": "http://vocab.lappsgrid.org/PhraseStructure",
                        "features": {
                            "constituents": "[c_0_0, c_0_1, c_0_2, c_0_3, c_0_4, c_0_5, c_0_6, c_0_7, c_0_8, c_0_9, c_0_10, c_0_11, c_0_12, c_0_13, c_0_14, c_0_15, c_0_16, c_0_17, **token-view:t_0, token-view:t_1, token-view:t_2, token-view:t_3, token-view:t_4, token-view:t_5**]"
                        }
                    }]

In the example of lif file (after TCF to LIF converter), token ids are found in constituents list. I think this is a minor bug.

**Comment by keighrim** [comment]
Duplicate to #7 . Closing the issue.
