### ISSUE TITLE
Token ids are coming in constituents list in  constituent parsing

### ISSUE THREAD

**Issue by elahi123** [lapps-clarin/converter-issues#7]
Hi 
The token ids are coming in constituents list after TCF to LIF converter 
{
                        "id": "ps_0",
                        "@type": "http://vocab.lappsgrid.org/PhraseStructure",
                        "features": {
                            "constituents": ["c_0_0", "c_0_1", "c_0_2", "c_0_3", "c_0_4", "c_0_5", "c_0_6", "c_0_7", "c_0_8", "c_0_9", "c_0_10", "c_0_11", **"t_0", "t_1", "t_2", "t_3", "t_4", "t_5"**]
                        }
                    }]
            }
Example file
[lif-viewref-test.txt](https://github.com/lapps-clarin/converter-issues/files/2328850/lif-viewref-test.txt)

**Comment by ksuderman** [comment]
This issue was moved to lappsgrid-services/org.lappsgrid.converters.tcf#22
