### ISSUE TITLE
Duplicate start id of two different tokens in LIF (on TCF to LIF converter)

### ISSUE THREAD

**Issue by elahi123** [lapps-clarin/converter-issues#8]
TCF to LIF converter sometimes generate wrong start ids. In the following example, two different (included, in) tokens have duplicate start id.  
Here is an example of 
[LIF-output.txt](https://github.com/lapps-clarin/converter-issues/files/2348886/LIF-output.txt)
[Tcf_Input.txt](https://github.com/lapps-clarin/converter-issues/files/2348891/Tcf_Input.txt)

duplicate start id of two tokens.

{
                        "id": "t_148",
                        "start": **791**,
                        "end": 799,
                        "@type": "http://vocab.lappsgrid.org/Token",
                        "features": {
                            "word": "included",
                            "pos": "VBN"
                        }
                    }, {
                        "id": "t_149",
                        "start": **791**,
                        "end": 793,
                        "@type": "http://vocab.lappsgrid.org/Token",
                        "features": {
                            "word": "in",
                            "pos": "IN"
                        }
                    },

**Comment by ksuderman** [comment]
This issue was moved to lappsgrid-services/org.lappsgrid.converters.tcf#21
